export const TABLE_COLUMNS_CONFIG = [
  {
    "pageId": "dashboard",
    "pageName": "Dashboard",
    "columns": [
      "Category",
      "Total Count",
      "Breakdown status"
    ]
  },
  {
    "pageId": "workspace",
    "pageName": "Workspace",
    "columns": [
      "Task ID",
      "Task Title",
      "Linked CRM Entity",
      "Category",
      "Priority",
      "Status",
      "Due Date",
      "Assignee",
      "Actions",
      "Policy Details",
      "Policy Number",
      "Year",
      "Commission Amount",
      "Rate",
      "Paid Date"
    ]
  },
  {
    "pageId": "contacts",
    "pageName": "Contacts",
    "columns": [
      "Name",
      "Phone",
      "Email",
      "City",
      "Stage",
      "Status",
      "Active",
      "File Name",
      "Document Title",
      "Description",
      "Actions",
      "Contact",
      "Phone / WhatsApp",
      "Opt-In Consent & Source",
      "Consent Action",
      "Enrolled Lists",
      "Lead Action"
    ]
  },
  {
    "pageId": "leads",
    "pageName": "Leads",
    "columns": [
      "Client Name",
      "Phone",
      "Product",
      "Exp. Premium",
      "Hotness",
      "Assigned To",
      "Stage",
      "Follow-up",
      "Lead Contact",
      "Insurance Product Interest",
      "Source Origin",
      "Est. Premium",
      "Pipeline Stage",
      "Captured At",
      "Actions"
    ]
  },
  {
    "pageId": "policies",
    "pageName": "Policies",
    "columns": [
      "Client Name",
      "Policy No",
      "Type",
      "Company",
      "Plan",
      "Premium",
      "Sum Insured",
      "Start Date",
      "Status"
    ]
  },
  {
    "pageId": "phc_tracking",
    "pageName": "PHC Tracking View",
    "columns": [
      "Insured Person",
      "Relationship",
      "Eligible Amount",
      "Utilized Amount",
      "Balance Amount",
      "Policy No",
      "Customer Name",
      "Product",
      "PHC Year",
      "Balance",
      "Status",
      "Days Left"
    ]
  },
  {
    "pageId": "emi_tracking",
    "pageName": "EMI Tracking View",
    "columns": [
      "Customer Name",
      "Policy No",
      "Product",
      "Due Date",
      "Amount",
      "EMIs",
      "Status",
      "Assigned To"
    ]
  },
  {
    "pageId": "claims",
    "pageName": "Claims",
    "columns": [
      "File Name",
      "Document Title",
      "Description",
      "Actions",
      "Claim No",
      "Client Name",
      "Policy No",
      "Company",
      "Type",
      "Hospital",
      "Amount",
      "Intimated At",
      "Status",
      "Claims",
      "Claimed",
      "Settled",
      "Time Range"
    ]
  },
  {
    "pageId": "whatsapp",
    "pageName": "WhatsApp",
    "columns": [
      "Template Name",
      "Category",
      "Dispatched",
      "Delivered",
      "Read Rate",
      "Reply Rate",
      "Leads Won",
      "Meta Cost",
      "Recipient",
      "Origin / Pipeline",
      "Template Used",
      "Scheduled & Sent",
      "Meta Status",
      "Delivery Audit & Error Diagnosis",
      "Retry Action",
      "Transaction ID",
      "Date & Time",
      "Amount Paid",
      "Bonus Credits",
      "Payment Mode",
      "Status",
      "Invoice",
      "Template & Meta Slug",
      "Header / Media",
      "Category & Lang",
      "CRM Variables",
      "Broadcast Stats",
      "Actions"
    ]
  },
  {
    "pageId": "operations",
    "pageName": "Operations / Master Settings",
    "columns": [
      "Module",
      "Description",
      "Records",
      "Last Exported",
      "Status",
      "Action",
      "Export Name",
      "Exported By",
      "Exported On",
      "File",
      "Plan Name",
      "Insurance Company",
      "Category",
      "Actions",
      "Rider Name",
      "Agent / Agency",
      "Contact Person",
      "Phone",
      "Email",
      "Hospital Info",
      "Claims Department",
      "Doctors",
      "Comment",
      "Policy & Business Type",
      "Company & Plan",
      "Valid Policy Periods",
      "Payment Options",
      "Payment Term (PPT)",
      "Field Name",
      "Field Label",
      "Required",
      "Dropdown Name",
      "Total Options",
      "Role Name",
      "Users",
      "User",
      "Details",
      "Date & Time",
      "Column Name",
      "Visibility"
    ]
  },
  {
    "pageId": "commissions",
    "pageName": "Commissions",
    "columns": [
      "Sr",
      "Policy No",
      "Beneficiary",
      "Amount",
      "Status",
      "Sr. No.",
      "Policy No.",
      "Customer Name",
      "Company",
      "Plan Name",
      "Policy Type",
      "Sum Insured",
      "Start Date",
      "End Date",
      "Agent",
      "Employee",
      "BA",
      "Manager",
      "Actions",
      "Company / Plan",
      "Premium"
    ]
  },
  {
    "pageId": "employees",
    "pageName": "Employees",
    "columns": [
      "Employee",
      "Leave Type",
      "Duration & Dates",
      "Days",
      "Reason / Remarks",
      "Status",
      "Approval Actions",
      "Policy / Client",
      "Insurer",
      "Sum Insured",
      "Premium",
      "Date Issued",
      "Date",
      "Shift Clock-In",
      "Shift Clock-Out",
      "Total Hours",
      "Calls",
      "Meetings",
      "Net Work Time",
      "Tasks",
      "Leads Moved",
      "Installments",
      "PHC",
      "Claims",
      "Premium (₹)",
      "Drill-Down",
      "Role & Department",
      "Key Responsibilities",
      "KPI Targets",
      "Workspace Status",
      "Action"
    ]
  },
  {
    "pageId": "subscription",
    "pageName": "Subscription",
    "columns": [
      "Module"
    ]
  },
  {
    "pageId": "superadmin",
    "pageName": "Superadmin",
    "columns": [
      "Agency",
      "Contact",
      "Users",
      "Policies",
      "Plan",
      "Status"
    ]
  }
];
