export const TABLE_COLUMNS_CONFIG = [
  {
    "pageId": "dashboard",
    "pageName": "Dashboard",
    "columns": [
      "Category",
      "Total Count",
      "Breakdown status"
    ]
  },
  {
    "pageId": "workspace",
    "pageName": "Workspace",
    "columns": [
      "Task ID",
      "Task Title",
      "Linked CRM Entity",
      "Category",
      "Priority",
      "Status",
      "Due Date",
      "Assignee",
      "Actions",
      "Policy Details",
      "Policy Number",
      "Year",
      "Commission Amount",
      "Rate",
      "Paid Date"
    ]
  },
  {
    "pageId": "contacts",
    "pageName": "Contacts",
    "columns": [
      "Contact ID",
      "Name",
      "Lead Stage",
      "Lead Status",
      "Next Follow-Up",
      "Assigned Employee",
      "Source",
      "Actions",
      "Product",
      "Renew Status",
      "Renew Assigned",
      "Claim Status",
      "Claim Assigned",
      "WA Campaign",
      "Phone",
      "Date of Birth",
      "Days Until Birthday",
      "Email",
      "City"
    ]
  },
  {
    "pageId": "leads",
    "pageName": "Leads",
    "columns": [
      "Client Name",
      "Phone",
      "Product",
      "Exp. Premium",
      "Hotness",
      "Assigned To",
      "Stage",
      "Follow-up",
      "Lead Contact",
      "Insurance Product Interest",
      "Source Origin",
      "Est. Premium",
      "Pipeline Stage",
      "Captured At",
      "Actions"
    ]
  },
  {
    "pageId": "policies",
    "pageName": "Policies",
    "columns": [
      "Proposer Name",
      "Proposer Contact No.",
      "City",
      "Customer Category",
      "Policy Type",
      "Policy Number",
      "Policy Status",
      "Sum Insured",
      "Policy Tenure",
      "Policy Term (Period of Coverage in Years)",
      "Assigned To",
      "Comment",
      "1st Year Premium Amount",
      "2nd Year Onwards Premium Amount",
      "Insurance Company Category",
      "Insurance Company",
      "Insurance Plan Category",
      "Plan Name"
    ]
  },
  {
    "pageId": "phc_tracking",
    "pageName": "PHC Tracking View",
    "columns": [
      "Sr. No.",
      "Customer Name",
      "Customer contact no",
      "Insurance company type",
      "Insurance company name",
      "Product name",
      "Sum Insured",
      "Policy no.",
      "Policy End date",
      "Current PHC Year",
      "PHC Year Start Date",
      "PHC Year End Date",
      "PHC Status",
      "PHC Amount",
      "Utilised Amount",
      "Balance amount",
      "Action",
      "Insured Person",
      "Relationship",
      "Eligible Amount"
    ]
  },
  {
    "pageId": "emi_tracking",
    "pageName": "EMI Tracking View",
    "columns": [
      "Customer Name",
      "Contact No.",
      "Insurance Type",
      "Insurer",
      "Product Name",
      "Policy No.",
      "Loan Provider",
      "Premium Amount",
      "Inst. Amount",
      "Frequency",
      "No. of Inst.",
      "Due Date",
      "Status",
      "Assigned Employee",
      "Actions"
    ]
  },
  {
    "pageId": "claims",
    "pageName": "Claims",
    "columns": [
      "Claim ID",
      "Client & Policy",
      "Claimed Amt",
      "Settled Amt",
      "Date Filed",
      "Status",
      "Actions",
      "Claim No",
      "Client Name",
      "Policy No",
      "Hospital",
      "Amount",
      "Intimated At"
    ]
  },
  {
    "pageId": "whatsapp",
    "pageName": "WhatsApp",
    "columns": [
      "Template Name",
      "Category",
      "Dispatched",
      "Delivered",
      "Read Rate",
      "Reply Rate",
      "Leads Won",
      "Meta Cost",
      "Recipient",
      "Origin / Pipeline",
      "Template Used",
      "Scheduled & Sent",
      "Meta Status",
      "Delivery Audit & Error Diagnosis",
      "Retry Action",
      "Transaction ID",
      "Date & Time",
      "Amount Paid",
      "Bonus Credits",
      "Payment Mode",
      "Status",
      "Invoice",
      "Template & Meta Slug",
      "Header / Media",
      "Category & Lang",
      "CRM Variables",
      "Broadcast Stats",
      "Actions"
    ]
  },
  {
    "pageId": "operations",
    "pageName": "Operations / Master Settings",
    "columns": [
      "Module",
      "Description",
      "Records",
      "Last Exported",
      "Status",
      "Action",
      "Export Name",
      "Exported By",
      "Exported On",
      "File",
      "Plan Name",
      "Insurance Company",
      "Category",
      "Actions",
      "Rider Name",
      "Agent / Agency",
      "Contact Person",
      "Phone",
      "Email",
      "Hospital Info",
      "Claims Department",
      "Doctors",
      "Comment",
      "Policy & Business Type",
      "Company & Plan",
      "Valid Policy Periods",
      "Payment Options",
      "Payment Term (PPT)",
      "Field Name",
      "Field Label",
      "Required",
      "Dropdown Name",
      "Total Options",
      "Role Name",
      "Users",
      "User",
      "Details",
      "Date & Time",
      "Column Name",
      "Visibility"
    ]
  },
  {
    "pageId": "commissions",
    "pageName": "Commissions",
    "columns": [
      "Sr",
      "Policy No",
      "Beneficiary",
      "Amount",
      "Status",
      "Sr. No.",
      "Policy No.",
      "Customer Name",
      "Company",
      "Plan Name",
      "Policy Type",
      "Sum Insured",
      "Start Date",
      "End Date",
      "Agent",
      "Employee",
      "BA",
      "Manager",
      "Actions",
      "Company / Plan",
      "Premium"
    ]
  },
  {
    "pageId": "employees",
    "pageName": "Employees",
    "columns": [
      "Employee",
      "Leave Type",
      "Duration & Dates",
      "Days",
      "Reason / Remarks",
      "Status",
      "Approval Actions",
      "Policy / Client",
      "Insurer",
      "Sum Insured",
      "Premium",
      "Date Issued",
      "Date",
      "Shift Clock-In",
      "Shift Clock-Out",
      "Total Hours",
      "Calls",
      "Meetings",
      "Net Work Time",
      "Tasks",
      "Leads Moved",
      "Installments",
      "PHC",
      "Claims",
      "Premium (₹)",
      "Drill-Down",
      "Role & Department",
      "Key Responsibilities",
      "KPI Targets",
      "Workspace Status",
      "Action"
    ]
  },
  {
    "pageId": "subscription",
    "pageName": "Subscription",
    "columns": [
      "Module"
    ]
  },
  {
    "pageId": "superadmin",
    "pageName": "Superadmin",
    "columns": [
      "Agency",
      "Contact",
      "Users",
      "Policies",
      "Plan",
      "Status"
    ]
  }
];
