export const MOCK_WHATSAPP_DATA = {
  agent: {
    name: 'Padmanabha Das',
    initials: 'PD',
    role: 'Agency Owner',
    agency: 'InfoYashonanada Insurance',
    phone: '+91 98765 43210',
    waNumber: '+91 98765 43210',
    waStatus: 'CONNECTED',
    businessId: '2847364918273645',
    phoneNumberId: '1928374650192837',
    walletBalance: 1450,
  },

  // ── Meta Phone Quality Rating & Daily Tier ──
  quality: {
    rating: 'HIGH' as const, // 'HIGH' (Green) | 'MEDIUM' (Yellow) | 'LOW' (Red)
    tier: 'Tier 2 (10,000 msgs / 24h)',
    tierLevel: 2,
    dailyLimit: 10000,
    dailyUsed: 1247,
    limitRemaining: 8753,
    blockReportRate: '0.12%', // Meta threshold is < 0.50%
    blockReportStatus: 'HEALTHY',
    qualityScore: 98, // out of 100
    lastSync: '2 minutes ago',
    history7Days: [
      { day: '15 Aug', quality: 'HIGH', score: 99, reports: 0 },
      { day: '16 Aug', quality: 'HIGH', score: 98, reports: 1 },
      { day: '17 Aug', quality: 'HIGH', score: 98, reports: 0 },
      { day: '18 Aug', quality: 'HIGH', score: 97, reports: 1 },
      { day: '19 Aug', quality: 'HIGH', score: 98, reports: 0 },
      { day: '20 Aug', quality: 'HIGH', score: 99, reports: 0 },
      { day: 'Today',  quality: 'HIGH', score: 98, reports: 0 },
    ],
    attentionAlerts: [
      { id: 'ALT01', type: 'TEMPLATE_REJECTED', severity: 'HIGH', title: 'Template "Claim Awareness Guide" was rejected by Meta', action: 'Fix Phrasing & Resubmit', tabTarget: 'templates' },
      { id: 'ALT02', type: 'FAILED_MESSAGES', severity: 'MEDIUM', title: '5 broadcast messages failed due to invalid numbers / network timeout', action: 'Retry 5 Failed Messages', tabTarget: 'history' },
      { id: 'ALT03', type: 'OPT_OUT', severity: 'LOW', title: '1 contact opted out via WhatsApp keyword "STOP"', action: 'View Opt-Out List', tabTarget: 'contacts' },
    ],
  },

  // ── Opt-In / Opt-Out Consent & Policy Rules ──
  optIn: {
    stats: {
      totalContacts: 4104,
      optedIn: 3890,
      optedOut: 34,
      pendingConsent: 180,
      optInRate: '94.8%',
      weeklyGrowth: '+3.2%',
    },
    settings: {
      optOutKeywords: ['STOP', 'UNSUBSCRIBE', 'OPTOUT', 'CANCEL', 'END'],
      optInKeywords: ['START', 'OPTIN', 'UNSTOP', 'YES', 'SUBSCRIBE'],
      autoStopOnOptOut: true,
      autoAppendOptOutNotice: true,
      optOutNoticeText: 'Reply STOP to unsubscribe anytime.',
      reOptInCooldownDays: 30,
    },
  },

  dashboard: {
    today: { total: 1247, sent: 1189, delivered: 1156, read: 892, failed: 58, replies: 143, leadsGenerated: 18 },
    week:  { total: 8420, sent: 8180, delivered: 7950, read: 6100, failed: 240, replies: 890, leadsGenerated: 94 },
    month: { total: 35600, sent: 34800, delivered: 33900, read: 26200, failed: 800, replies: 3800, leadsGenerated: 420 },
    active: { automations: 7, campaigns: 3, pendingApprovals: 2, upcomingMessages: 47 },
    attention: { failed: 5, invalidNumbers: 3, templateRejected: 1, optedOut: 34, campaignErrors: 1 },
    deliveryRate: 97.2,
    readRate: 77.1,
    replyRate: 12.4,
    leadConversionRate: 4.8,
    chartData: [
      { day: 'Mon', sent: 1180, delivered: 1150, read: 890, leads: 14 },
      { day: 'Tue', sent: 1240, delivered: 1210, read: 940, leads: 18 },
      { day: 'Wed', sent: 980,  delivered: 952,  read: 720, leads: 9 },
      { day: 'Thu', sent: 1350, delivered: 1320, read: 1040, leads: 22 },
      { day: 'Fri', sent: 1420, delivered: 1390, read: 1100, leads: 25 },
      { day: 'Sat', sent: 820,  delivered: 800,  read: 620, leads: 8 },
      { day: 'Sun', sent: 430,  delivered: 420,  read: 310, leads: 4 },
    ],
  },

  upcoming: [
    { id: 'U001', contact: 'Rajesh Kumar', avatar: 'RK', color: 'bg-blue-500', type: 'Renewal Reminder', detail: '30 days before renewal', time: '10:00 AM', date: 'Today' },
    { id: 'U002', contact: 'Amit Sharma', avatar: 'AS', color: 'bg-emerald-500', type: 'Installment Reminder', detail: '3 days before installment', time: '11:00 AM', date: 'Today' },
    { id: 'U003', contact: 'Kavita Joshi', avatar: 'KJ', color: 'bg-cyan-500', type: 'Birthday Greetings', detail: 'Birthday today 🎂', time: '08:00 AM', date: 'Today' },
    { id: 'U004', contact: 'Mohan Lal', avatar: 'ML', color: 'bg-rose-500', type: 'Grace Period Alert', detail: '+1 day after expiry', time: '11:30 AM', date: 'Today' },
    { id: 'U005', contact: 'Deepa Gupta', avatar: 'DG', color: 'bg-indigo-500', type: 'Renewal Reminder', detail: '45 days before renewal', time: '10:00 AM', date: 'Tomorrow' },
    { id: 'U006', contact: 'Vikram Rao', avatar: 'VR', color: 'bg-teal-500', type: 'PHC Reminder', detail: '240 days — PHC due', time: '09:00 AM', date: 'Tomorrow' },
  ],

  conversations: [
    {
      id: 'CONV001',
      contactId: 'C001',
      name: 'Rajesh Kumar',
      phone: '+91 98100 11111',
      avatar: 'RK',
      color: 'bg-blue-500',
      lastMsg: 'When will my policy expire exactly?',
      lastMsgTime: '10:32 AM',
      unread: 2,
      online: true,
      hasLead: false,
      // 24h Customer Service Window
      isServiceWindowActive: true,
      serviceWindowExpiresAt: new Date(Date.now() + 18.7 * 3600000).toISOString(),
      serviceWindowTimeText: '18h 42m remaining',
      assignedTo: 'Padmanabha Das',
      tags: ['Hot Lead', 'Renewal Due'],
      status: 'OPEN',
      notes: 'Customer inquired about 25L Sum Insured upgrade. Prepared quote comparison.',
      origin: { type: 'AUTOMATION', name: 'Renewal Reminder Series', id: 'A001' },
      messages: [
        { id: 1, from: 'out', type: 'template', templateName: 'Renewal Reminder', body: 'Hello Rajesh,\n\nYour Star Health policy *SH-2024-88821* is due for renewal on *20-Oct-2026*.\n\nPremium Amount: ₹24,500\n\nPlease renew before expiry.', time: '09:00 AM', status: 'READ' },
        { id: 2, from: 'in', type: 'text', body: 'Thanks for the reminder! When exactly does it expire?', time: '09:45 AM' },
        { id: 3, from: 'out', type: 'text', body: 'Your policy expires on 20th October 2026. I recommend renewing before 15th Oct. Shall I send you the renewal payment link?', time: '09:50 AM', status: 'READ' },
        { id: 4, from: 'in', type: 'text', body: 'Yes please. Also, can I increase my sum insured to 25 Lakhs?', time: '10:28 AM' },
        { id: 5, from: 'in', type: 'text', body: 'When will my policy expire exactly?', time: '10:32 AM' },
      ],
      crm: {
        city: 'Pune',
        email: 'rajesh.kumar@example.com',
        policies: [{ name: 'Star Health Optima', no: 'SH-2024-88821', type: 'Health', renewal: '20 Oct 2026', premium: '₹24,500' }],
        campaigns: ['Renewal Reminder Series', 'Health Awareness Aug'],
        suggestedInterest: 'Health Insurance (Sum Insured Upgrade)',
      },
    },
    {
      id: 'CONV002',
      contactId: 'C002',
      name: 'Priya Singh',
      phone: '+91 98200 22222',
      avatar: 'PS',
      color: 'bg-purple-500',
      lastMsg: 'Ok, noted. Thank you!',
      lastMsgTime: '2 days ago',
      unread: 0,
      online: false,
      hasLead: true,
      // 24h Customer Service Window - EXPIRED
      isServiceWindowActive: false,
      serviceWindowExpiresAt: new Date(Date.now() - 5.4 * 3600000).toISOString(),
      serviceWindowTimeText: 'Window Expired',
      assignedTo: 'Priya Sharma',
      tags: ['PHC Claimed', 'Customer'],
      status: 'RESOLVED',
      notes: 'Customer booked PHC slot at Ruby Hall Clinic Pune.',
      origin: { type: 'AUTOMATION', name: 'PHC Cycle Reminder', id: 'A004' },
      messages: [
        { id: 1, from: 'out', type: 'template', templateName: 'PHC Reminder', body: 'Dear Priya,\n\nYour PHC benefit under policy NIA-2023-55421 is available.\n\n📅 Policy Year: Year 2\n💰 Available Balance: ₹10,000\n\nBook your check-up before the year ends.', time: 'Tue 09:00 AM', status: 'READ' },
        { id: 2, from: 'in', type: 'text', body: 'Thank you! Where can I find the list of partner hospitals?', time: 'Tue 11:30 AM' },
        { id: 3, from: 'out', type: 'text', body: 'I am sharing the network hospitals in Mumbai below. You can also book directly via the portal.', time: 'Tue 11:35 AM', status: 'READ' },
        { id: 4, from: 'in', type: 'text', body: 'Ok, noted. Thank you!', time: 'Tue 11:40 AM' },
      ],
      crm: {
        city: 'Mumbai',
        email: 'priya.singh@example.com',
        policies: [{ name: 'New India Assurance Mediclaim', no: 'NIA-2023-55421', type: 'Health', renewal: '15 Mar 2027', premium: '₹18,000' }],
        campaigns: ['Health Awareness Aug'],
        suggestedInterest: 'Preventive Health Checkup (PHC)',
      },
    },
    {
      id: 'CONV003',
      contactId: 'C003',
      name: 'Amit Sharma',
      phone: '+91 98300 33333',
      avatar: 'AS',
      color: 'bg-emerald-500',
      lastMsg: 'Yes, please proceed with the term insurance quote.',
      lastMsgTime: 'Yesterday, 03:30 PM',
      unread: 1,
      online: true,
      hasLead: false,
      // 24h Customer Service Window - ACTIVE
      isServiceWindowActive: true,
      serviceWindowExpiresAt: new Date(Date.now() + 6.2 * 3600000).toISOString(),
      serviceWindowTimeText: '6h 12m remaining',
      assignedTo: 'Padmanabha Das',
      tags: ['High Intent', 'Term Quote'],
      status: 'OPEN',
      notes: 'Requested 2 Cr cover quote comparison for 35yo non-smoker.',
      origin: { type: 'CAMPAIGN', name: 'Term Insurance Awareness', id: 'CAM002' },
      messages: [
        { id: 1, from: 'out', type: 'template', templateName: 'Term Plan Benefit', body: 'Hello Amit,\n\nSecure your family\'s financial future with 1 Crore term cover starting @ ₹650/month.\n\nReply YES to get an instant quote.', time: 'Mon 10:00 AM', status: 'READ' },
        { id: 2, from: 'in', type: 'text', body: 'Hi, I am interested. Can I get a quote for a 35-year-old non-smoker for 2 Crore cover?', time: 'Mon 02:15 PM' },
        { id: 3, from: 'out', type: 'text', body: 'Certainly Amit! For 2 Crore cover up to age 70, the premium will be approx ₹18,200/year. Shall I prepare the comparison sheet?', time: 'Mon 02:20 PM', status: 'READ' },
        { id: 4, from: 'in', type: 'text', body: 'Yes, please proceed with the term insurance quote.', time: 'Mon 03:30 PM' },
      ],
      crm: {
        city: 'Pune',
        email: 'amit.sharma@example.com',
        policies: [{ name: 'ICICI Lombard Health', no: 'ICICI-2024-33142', type: 'Health', renewal: '01 Sep 2026', premium: '₹31,200' }],
        campaigns: ['Renewal Reminder Series', 'Term Plan Awareness'],
        suggestedInterest: 'Term Life Insurance',
      },
    },
  ],

  automations: [
    {
      id: 'A001',
      name: 'Renewal Reminder Series',
      category: 'Policy',
      trigger: 'POLICY_RENEWAL_DATE',
      status: 'ACTIVE',
      schedules: ['45d before', '30d before', '15d before', '7d before', '3d before', '1d before'],
      conditions: ['Policy Status = ACTIVE', 'WhatsApp Opt-in = TRUE'],
      stopConditions: ['Policy Renewed', 'Policy Cancelled', 'Policy Inactive'],
      autoGenerateLeadOnReply: true,
      template: 'Renewal Reminder',
      nextRun: 'Today, 10:00 AM',
      sent: 12500,
      delivered: 12100,
      read: 9800,
      replied: 1250,
      leadsGenerated: 142,
      // Backend mapping
      backendQueue: 'policy-renewal',
      backendJob: 'scan-renewals → notify-renewal',
      cronSchedule: '07:00 IST daily',
      dataSource: 'Policy.endDate',
      description: 'Scans all active policies daily at 07:00 IST. For each policy expiring within 45 days, it fans out per-policy notify jobs that send renewal reminders via WhatsApp template at each configured offset.',
      pipelineSteps: [
        { icon: 'clock', label: 'Daily Scan', detail: '07:00 IST Cron' },
        { icon: 'filter', label: 'Filter', detail: 'Active policies expiring in 1–45 days' },
        { icon: 'template', label: 'Send Template', detail: 'Renewal Reminder' },
        { icon: 'lead', label: 'Lead Capture', detail: 'On customer reply' },
      ],
      group: 'policy-lifecycle',
    },
    {
      id: 'A002',
      name: 'Installment Reminder',
      category: 'Policy',
      trigger: 'INSTALLMENT_DATE',
      status: 'ACTIVE',
      schedules: ['6d before', '3d before', '3d after'],
      conditions: ['Policy Status = ACTIVE', 'WhatsApp Opt-in = TRUE', 'Payment Freq ≠ YEARLY'],
      stopConditions: ['Installment Paid'],
      autoGenerateLeadOnReply: false,
      template: 'Installment Reminder',
      nextRun: '22 Aug, 09:00 AM',
      sent: 8200,
      delivered: 8050,
      read: 6300,
      replied: 420,
      leadsGenerated: 18,
      // Backend mapping
      backendQueue: 'payment-reminder',
      backendJob: 'scan-payments → notify-payment',
      cronSchedule: '08:00 IST daily',
      dataSource: 'PolicyPayment.dueDate',
      description: 'Scans unpaid policy payments daily at 08:00 IST. Sends reminders 6 days before, 3 days before, and 3 days after the due date for non-yearly payment frequencies.',
      pipelineSteps: [
        { icon: 'clock', label: 'Daily Scan', detail: '08:00 IST Cron' },
        { icon: 'filter', label: 'Filter', detail: 'Unpaid installments, Freq ≠ YEARLY' },
        { icon: 'template', label: 'Send Template', detail: 'Installment Reminder' },
        { icon: 'stop', label: 'Auto-Stop', detail: 'When paid' },
      ],
      group: 'policy-lifecycle',
    },
    {
      id: 'A003',
      name: 'Grace Period Alert',
      category: 'Policy',
      trigger: 'POLICY_END_DATE',
      status: 'ACTIVE',
      schedules: ['+1 day', '+5 days', '+10 days', '+15 days', '+20 days', '+25 days', '+28 days'],
      conditions: ['Policy Expired', 'Policy Not Renewed', 'WhatsApp Opt-in = TRUE'],
      stopConditions: ['Policy Renewed'],
      autoGenerateLeadOnReply: true,
      template: 'Renewal Reminder',
      nextRun: '21 Aug, 11:00 AM',
      sent: 1100,
      delivered: 1070,
      read: 820,
      replied: 95,
      leadsGenerated: 48,
      // Backend mapping
      backendQueue: 'policy-renewal',
      backendJob: 'scan-renewals → notify-renewal',
      cronSchedule: '07:00 IST daily',
      dataSource: 'Policy.endDate (post-expiry)',
      description: 'Part of the same renewal scan job. For policies that have already expired but are within the 30-day grace window, sends escalating urgency reminders to re-engage lapsed customers.',
      pipelineSteps: [
        { icon: 'clock', label: 'Daily Scan', detail: '07:00 IST Cron' },
        { icon: 'filter', label: 'Filter', detail: 'Expired 1–28 days, not renewed' },
        { icon: 'template', label: 'Send Template', detail: 'Renewal Reminder (Urgent)' },
        { icon: 'lead', label: 'Lead Capture', detail: 'On customer reply' },
      ],
      group: 'policy-lifecycle',
    },
    {
      id: 'A004',
      name: 'PHC Cycle Reminder',
      category: 'PHC',
      trigger: 'PHC_CYCLE_START',
      status: 'PAUSED',
      schedules: ['120d', '180d', '240d', '270d', '300d', '330d', '350d'],
      conditions: ['Policy Status = ACTIVE', 'PHC Completed = FALSE', 'Policy Type = HEALTH'],
      stopConditions: ['PHC Completed = TRUE'],
      autoGenerateLeadOnReply: true,
      template: 'PHC Reminder',
      nextRun: '—',
      sent: 4300,
      delivered: 4180,
      read: 3200,
      replied: 280,
      leadsGenerated: 34,
      pauseReason: 'Template pending Meta approval',
      // Backend mapping
      backendQueue: 'reminders',
      backendJob: 'scan-health-checkups → health-checkup',
      cronSchedule: '09:00 IST daily',
      dataSource: 'PreventiveHealthCheckup.scheduledAt',
      description: 'Scans health policies daily for contacts eligible for free Preventive Health Check-up. Sends staged reminders from 120 days through 350 days into the policy year until PHC is completed.',
      pipelineSteps: [
        { icon: 'clock', label: 'Daily Scan', detail: '09:00 IST Cron' },
        { icon: 'filter', label: 'Filter', detail: 'Health policy, PHC not availed' },
        { icon: 'template', label: 'Send Template', detail: 'PHC Reminder' },
        { icon: 'lead', label: 'Lead Capture', detail: 'On customer reply' },
      ],
      group: 'customer-events',
    },
    {
      id: 'A005',
      name: 'Birthday Greetings',
      category: 'Customer',
      trigger: 'CUSTOMER_BIRTHDAY',
      status: 'ACTIVE',
      schedules: ['Same day 08:00 AM'],
      conditions: ['Insured Attached to Active Policy', 'WhatsApp Opt-in = TRUE'],
      stopConditions: ['Already sent this year'],
      autoGenerateLeadOnReply: false,
      template: 'Birthday Wishes',
      nextRun: 'Today, 08:00 AM',
      sent: 28,
      delivered: 27,
      read: 24,
      replied: 8,
      leadsGenerated: 2,
      // Backend mapping
      backendQueue: 'reminders',
      backendJob: 'scan-birthdays → birthday-wish',
      cronSchedule: '07:30 IST daily',
      dataSource: 'Contact.dateOfBirth',
      description: 'Scans all contacts daily at 07:30 IST. For contacts whose birthday matches today, sends a personalized birthday greeting via WhatsApp at 08:00 AM.',
      pipelineSteps: [
        { icon: 'clock', label: 'Daily Scan', detail: '07:30 IST Cron' },
        { icon: 'filter', label: 'Filter', detail: 'Birthday = Today, Opt-in = TRUE' },
        { icon: 'template', label: 'Send Greeting', detail: 'Birthday Wishes' },
      ],
      group: 'customer-events',
    },
    {
      id: 'A006',
      name: 'Policy Thank-You',
      category: 'Events',
      trigger: 'POLICY_CREATED',
      status: 'ACTIVE',
      schedules: ['Immediately on event'],
      conditions: ['WhatsApp Opt-in = TRUE'],
      stopConditions: ['Already sent for this policy'],
      autoGenerateLeadOnReply: false,
      template: 'Policy Thank You',
      nextRun: 'On event',
      sent: 890,
      delivered: 878,
      read: 820,
      replied: 110,
      leadsGenerated: 12,
      // Backend mapping
      backendQueue: 'whatsapp-campaigns',
      backendJob: 'triggerEventCampaign(POLICY_CREATED)',
      cronSchedule: 'Real-time event',
      dataSource: 'WhatsappCampaign.targetFilters.eventTrigger',
      description: 'Triggered instantly when a new policy is created in the CRM. Uses the WhatsApp campaign event trigger system to send a welcome message with policy PDF and thank-you note.',
      pipelineSteps: [
        { icon: 'event', label: 'Event Trigger', detail: 'Policy Created in CRM' },
        { icon: 'template', label: 'Send Template', detail: 'Policy Thank You' },
        { icon: 'stop', label: 'Dedup', detail: 'Once per policy' },
      ],
      group: 'smart-triggers',
    },
    {
      id: 'A007',
      name: 'Follow-Up Reminder',
      category: 'Customer',
      trigger: 'FOLLOW_UP_DATE',
      status: 'ACTIVE',
      schedules: ['Same day 09:00 AM'],
      conditions: ['Lead follow_up_date = Today', 'Lead stage ≠ PROCESS_COMPLETED'],
      stopConditions: ['Follow-up completed', 'Lead closed'],
      autoGenerateLeadOnReply: true,
      template: 'Follow-Up Reminder',
      nextRun: 'Tomorrow, 09:00 AM',
      sent: 560,
      delivered: 548,
      read: 420,
      replied: 62,
      leadsGenerated: 28,
      // Backend mapping
      backendQueue: 'reminders',
      backendJob: 'scan-follow-ups → follow-up',
      cronSchedule: '08:30 IST daily',
      dataSource: 'ProductInterest.followUpDate',
      description: 'Scans all leads with follow-up dates matching today. Sends a reminder notification to the assigned employee and optionally a WhatsApp nudge to the customer.',
      pipelineSteps: [
        { icon: 'clock', label: 'Daily Scan', detail: '08:30 IST Cron' },
        { icon: 'filter', label: 'Filter', detail: 'Follow-up date = Today' },
        { icon: 'template', label: 'Send Reminder', detail: 'Follow-Up Reminder' },
        { icon: 'lead', label: 'Lead Update', detail: 'Mark as contacted' },
      ],
      group: 'customer-events',
    },
  ],

  campaigns: [
    {
      id: 'CAM001',
      name: 'Diwali Greetings 2026',
      type: 'Scheduled',
      category: 'Festival',
      audience: 4200,
      template: 'Festival Greeting',
      templateId: 'T002',
      media: 'Diwali Flyer 2026',
      scheduledDate: '20 Oct 2026, 09:00 AM',
      status: 'SCHEDULED',
      sent: 0,
      delivered: 0,
      read: 0,
      failed: 0,
      replied: 0,
      leadsGenerated: 0,
      autoCaptureLeads: true,
      costPerMsg: 1.0,
      totalCost: 4200,
      backendQueue: 'whatsapp-campaigns',
      backendJob: 'send-campaign (delay scheduled)',
      targetFilters: {
        lists: ['Doctors', 'Engineers', 'Existing Customers', 'Rotary'],
        optInOnly: true,
        excludeInvalid: true,
        triggerType: 'scheduled',
        festivalName: 'Diwali',
      },
    },
    {
      id: 'CAM002',
      name: 'Claim Awareness H1 2026',
      type: 'Recurring',
      category: 'Health',
      audience: 2890,
      template: 'Claim Awareness Guide',
      templateId: 'T004',
      media: 'Claim Process Guide PDF',
      scheduledDate: '15 Mar 2026, 10:00 AM',
      status: 'COMPLETED',
      sent: 2856,
      delivered: 2801,
      read: 2190,
      failed: 34,
      replied: 185,
      leadsGenerated: 42,
      autoCaptureLeads: true,
      costPerMsg: 1.0,
      totalCost: 2856,
      backendQueue: 'whatsapp-campaigns',
      backendJob: 'send-campaign (completed)',
      targetFilters: {
        lists: ['Existing Customers', 'Health Leads'],
        optInOnly: true,
        excludeInvalid: true,
        triggerType: 'recurring',
      },
    },
    {
      id: 'CAM003',
      name: 'MF & Tax Saving Drive',
      type: 'One-time',
      category: 'Promotion',
      audience: 1245,
      template: 'Festival Greeting',
      templateId: 'T002',
      media: 'MF Returns Infographic',
      scheduledDate: '25 Aug 2026, 10:00 AM',
      status: 'DRAFT',
      sent: 0,
      delivered: 0,
      read: 0,
      failed: 0,
      replied: 0,
      leadsGenerated: 0,
      autoCaptureLeads: true,
      costPerMsg: 1.0,
      totalCost: 1245,
      backendQueue: 'whatsapp-campaigns',
      backendJob: 'send-campaign (pending launch)',
      targetFilters: {
        lists: ['Engineers', 'Doctors', 'BNI Members'],
        optInOnly: true,
        excludeInvalid: true,
        triggerType: 'manual',
      },
    },
    {
      id: 'CAM004',
      name: 'Health Awareness August',
      type: 'One-time',
      category: 'Health',
      audience: 3100,
      template: 'Health Awareness',
      templateId: 'T003',
      media: 'Health Awareness Reel',
      scheduledDate: '15 Aug 2026, 09:00 AM',
      status: 'RUNNING',
      sent: 2450,
      delivered: 2390,
      read: 1980,
      failed: 60,
      replied: 220,
      leadsGenerated: 38,
      progress: 79,
      autoCaptureLeads: true,
      costPerMsg: 1.0,
      totalCost: 3100,
      backendQueue: 'whatsapp-campaigns',
      backendJob: 'send-campaign (active worker dispatch)',
      targetFilters: {
        lists: ['Health Leads', 'Doctors'],
        optInOnly: true,
        excludeInvalid: true,
        triggerType: 'manual',
      },
    },
    {
      id: 'CAM005',
      name: 'Term Cover 2Cr Upgrade Blitz',
      type: 'One-time',
      category: 'Promotion',
      audience: 1850,
      template: 'Renewal Reminder',
      templateId: 'T001',
      media: 'Policy Renewal Card',
      scheduledDate: '10 Aug 2026, 11:00 AM',
      status: 'PAUSED',
      sent: 650,
      delivered: 635,
      read: 480,
      failed: 15,
      replied: 45,
      leadsGenerated: 14,
      progress: 35,
      autoCaptureLeads: true,
      costPerMsg: 1.0,
      totalCost: 1850,
      pauseReason: 'Wallet top-up required to complete remaining batch',
      backendQueue: 'whatsapp-campaigns',
      backendJob: 'send-campaign (paused on threshold)',
      targetFilters: {
        lists: ['BNI Members', 'MF Leads', 'Existing Customers'],
        optInOnly: true,
        excludeInvalid: true,
        triggerType: 'manual',
      },
    },
  ],

  templates: [
    {
      id: 'T001',
      name: 'Renewal Reminder',
      category: 'UTILITY',
      language: 'English (en_US)',
      status: 'APPROVED',
      metaTemplateId: 'waba_tpl_88192301',
      headerType: 'TEXT',
      headerText: 'IMPORTANT: POLICY RENEWAL',
      headerMediaUrl: null,
      variables: 5,
      body: 'Hello {{1}},\n\nYour {{2}} health policy *{{3}}* is due for renewal on *{{4}}*.\n\nPremium Amount: ₹{{5}}\n\nPlease renew before expiry to avoid coverage gaps.',
      variables_map: [
        ['1', 'Customer Name', 'Contact.firstName', 'Rajesh Kumar'],
        ['2', 'Insurer Name', 'Policy.insurerName', 'Star Health'],
        ['3', 'Policy Number', 'Policy.policyNumber', 'SH-2024-88821'],
        ['4', 'Renewal Date', 'Policy.endDate', '20-Oct-2026'],
        ['5', 'Premium Amount', 'Policy.premiumAmount', '24,500'],
      ],
      buttons: [
        { type: 'QUICK_REPLY', text: '💳 Pay Online Link' },
        { type: 'QUICK_REPLY', text: '👤 Talk to Advisor' },
        { type: 'URL', text: 'View Policy PDF', url: 'https://insumitra.com/p/{{3}}' },
      ],
      footer: 'InfoYashonanada Insurance · Reply STOP to opt out',
      lastUsed: '18 Aug 2026',
      usageCount: 3,
      sent: 12500,
      delivered: 12100,
      read: 9800,
      replied: 1250,
    },
    {
      id: 'T002',
      name: 'Festival Greeting',
      category: 'MARKETING',
      language: 'English (en_US)',
      status: 'APPROVED',
      metaTemplateId: 'waba_tpl_77182902',
      headerType: 'IMAGE',
      headerText: null,
      headerMediaUrl: '/assets/media/diwali_flyer_2026.png',
      headerMediaName: 'Diwali Flyer 2026',
      variables: 2,
      body: 'Dear {{1}},\n\nWarm wishes to you and your family on the occasion of *{{2}}*! 🎉\n\nMay this festive season bring immense health, happiness, and prosperity.\n\nWith warm regards,\nYour Insurance Advisor',
      variables_map: [
        ['1', 'Customer Name', 'Contact.firstName', 'Rajesh Kumar'],
        ['2', 'Festival Name', 'Campaign.festivalName', 'Diwali 2026'],
      ],
      buttons: [
        { type: 'QUICK_REPLY', text: '🙏 Thank You' },
        { type: 'QUICK_REPLY', text: '🛡️ Check Policy Review' },
      ],
      footer: 'InfoYashonanada Insurance',
      lastUsed: '15 Aug 2026',
      usageCount: 2,
      sent: 4200,
      delivered: 4120,
      read: 3450,
      replied: 410,
    },
    {
      id: 'T003',
      name: 'PHC Reminder',
      category: 'UTILITY',
      language: 'English (en_US)',
      status: 'PENDING',
      metaTemplateId: 'waba_tpl_66192803',
      headerType: 'IMAGE',
      headerText: null,
      headerMediaUrl: '/assets/media/phc_benefit_card.png',
      headerMediaName: 'PHC Benefit Card',
      variables: 4,
      body: 'Dear {{1}},\n\nYour *Preventive Health Check-up (PHC)* benefit under policy {{2}} is available.\n\n📅 Policy Year: {{3}}\n💰 Available Balance: ₹{{4}}\n\nBook your check-up before the year ends to avail your complimentary benefit.',
      variables_map: [
        ['1', 'Customer Name', 'Contact.firstName', 'Priya Singh'],
        ['2', 'Policy Number', 'Policy.policyNumber', 'NIA-2023-55421'],
        ['3', 'Policy Year', 'Policy.policyYear', 'Year 2'],
        ['4', 'PHC Balance', 'Policy.phcBalance', '10,000'],
      ],
      buttons: [
        { type: 'QUICK_REPLY', text: '🏥 Book Slot in Pune' },
        { type: 'QUICK_REPLY', text: '📋 View Diagnostic Labs' },
      ],
      footer: 'InfoYashonanada Insurance',
      usageCount: 1,
      sent: 0,
      delivered: 0,
      read: 0,
      replied: 0,
    },
    {
      id: 'T004',
      name: 'Claim Awareness Guide',
      category: 'UTILITY',
      language: 'English (en_US)',
      status: 'REJECTED',
      metaTemplateId: 'waba_tpl_55102904',
      headerType: 'DOCUMENT',
      headerText: null,
      headerMediaUrl: '/assets/media/claim_guide.pdf',
      headerMediaName: 'Claim Process Guide PDF',
      variables: 1,
      body: 'Dear {{1}},\n\n⚠️ Important: Before hospitalization, please inform us within 24 hours for guaranteed cashless claim processing.\n\nFor reimbursement claims, keep all original bills and reports.\n\nCall our 24/7 Claim Desk: +91 98765 43210',
      variables_map: [
        ['1', 'Customer Name', 'Contact.firstName', 'Amit Sharma'],
      ],
      buttons: [
        { type: 'PHONE_NUMBER', text: '📞 Call Claim Desk', phone: '+919876543210' },
        { type: 'QUICK_REPLY', text: 'Intimate Claim Now' },
      ],
      footer: 'InfoYashonanada Insurance',
      rejectReason: 'Meta policy violation: Promissory language "guaranteed cashless claim" violates WhatsApp Business Policy §4.3 (Insurance disclaimers).',
      rejectSuggestion: 'Change "guaranteed cashless claim processing" to "seamless cashless claim assistance" and resubmit for immediate review.',
      usageCount: 1,
      sent: 0,
      delivered: 0,
      read: 0,
      replied: 0,
    },
    {
      id: 'T005',
      name: 'Birthday Wishes',
      category: 'MARKETING',
      language: 'Hindi (hi)',
      status: 'APPROVED',
      metaTemplateId: 'waba_tpl_44182905',
      headerType: 'NONE',
      headerText: null,
      headerMediaUrl: null,
      variables: 1,
      body: 'प्रिय {{1}},\n\nआपको जन्मदिन की हार्दिक शुभकामनाएँ! 🎂🎉\n\nईश्वर आपको दीर्घायु, उत्तम स्वास्थ्य और अपार समृद्धि प्रदान करें।\n\nसस्नेह,\nInfoYashonanada Insurance Team',
      variables_map: [
        ['1', 'Customer Name', 'Contact.firstName', 'Dr. Kavita Joshi'],
      ],
      buttons: [
        { type: 'QUICK_REPLY', text: '🙏 धन्यवाद' },
      ],
      footer: 'InfoYashonanada Insurance',
      usageCount: 1,
      sent: 28,
      delivered: 27,
      read: 24,
      replied: 8,
    },
  ],

  contacts: [
    {
      id: 'C001',
      name: 'Rajesh Kumar',
      phone: '+91 98100 11111',
      wa: '+91 98100 11111',
      optIn: true,
      optInStatus: 'OPTED_IN' as const,
      optInSource: 'Web Form Opt-In',
      optInTimestamp: '12 Jan 2026, 14:30',
      city: 'Pune',
      lists: ['Doctors', 'Existing Customers'],
      lastMsg: '10 Aug 2026',
      tags: ['health', 'renewal', 'vip'],
      avatar: 'RK',
      color: 'bg-blue-500',
      policyType: 'Health',
      sumInsured: '15 Lakhs',
      policyNo: 'SH-2024-88821',
      expiryDate: '20-Oct-2026',
      premium: '₹24,500',
    },
    {
      id: 'C002',
      name: 'Priya Singh',
      phone: '+91 98200 22222',
      wa: '+91 98200 22222',
      optIn: true,
      optInStatus: 'OPTED_IN' as const,
      optInSource: 'Policy Application Form',
      optInTimestamp: '15 Mar 2025, 11:20',
      city: 'Mumbai',
      lists: ['Health Leads'],
      lastMsg: '15 Aug 2026',
      tags: ['lead', 'health', 'phc'],
      avatar: 'PS',
      color: 'bg-purple-500',
      policyType: 'Health',
      sumInsured: '10 Lakhs',
      policyNo: 'NIA-2023-55421',
      expiryDate: '15-Mar-2027',
      premium: '₹18,000',
    },
    {
      id: 'C003',
      name: 'Amit Sharma',
      phone: '+91 98300 33333',
      wa: '+91 98300 33333',
      optIn: true,
      optInStatus: 'OPTED_IN' as const,
      optInSource: 'Inbound WhatsApp Inquiry',
      optInTimestamp: '05 Feb 2026, 16:45',
      city: 'Pune',
      lists: ['BNI Members', 'MF Leads'],
      lastMsg: '12 Aug 2026',
      tags: ['mf', 'term', 'renewal'],
      avatar: 'AS',
      color: 'bg-emerald-500',
      policyType: 'Term Life',
      sumInsured: '1 Crore',
      policyNo: 'ICICI-2024-33142',
      expiryDate: '01-Sep-2026',
      premium: '₹31,200',
    },
    {
      id: 'C004',
      name: 'Sunita Devi',
      phone: '+91 98400 44444',
      wa: '—',
      optIn: false,
      optInStatus: 'OPTED_OUT' as const,
      optInSource: 'Opted Out via "STOP" keyword',
      optInTimestamp: '10 Aug 2026, 09:12',
      city: 'Nashik',
      lists: ['Engineers'],
      lastMsg: '—',
      tags: ['health', 'opted_out'],
      avatar: 'SD',
      color: 'bg-amber-500',
      invalid: true,
      policyType: 'Motor',
      sumInsured: '5 Lakhs',
      policyNo: 'BAGIC-2024-1102',
      expiryDate: '12-Nov-2026',
      premium: '₹7,500',
    },
    {
      id: 'C005',
      name: 'Mohan Lal',
      phone: '+91 98500 55555',
      wa: '+91 98500 55555',
      optIn: true,
      optInStatus: 'OPTED_IN' as const,
      optInSource: 'Direct Consent Form',
      optInTimestamp: '20 Apr 2025, 10:15',
      city: 'Pune',
      lists: ['Rotary', 'Existing Customers'],
      lastMsg: '18 Aug 2026',
      tags: ['term', 'renewal', 'installment'],
      avatar: 'ML',
      color: 'bg-rose-500',
      policyType: 'Health & Term',
      sumInsured: '25 Lakhs',
      policyNo: 'HDFC-2023-9901',
      expiryDate: '24-Aug-2026',
      premium: '₹42,000',
    },
    {
      id: 'C006',
      name: 'Kavita Joshi',
      phone: '+91 98600 66666',
      wa: '+91 98600 66666',
      optIn: true,
      optInStatus: 'OPTED_IN' as const,
      optInSource: 'Policy Application Form',
      optInTimestamp: '01 Jun 2025, 12:00',
      city: 'Pune',
      lists: ['Doctors'],
      lastMsg: '14 Aug 2026',
      tags: ['health', 'phc', 'birthday'],
      avatar: 'KJ',
      color: 'bg-cyan-500',
      isBirthday: true,
      policyType: 'Health',
      sumInsured: '20 Lakhs',
      policyNo: 'STAR-2024-7712',
      expiryDate: '05-Dec-2026',
      premium: '₹28,400',
    },
    {
      id: 'C007',
      name: 'Vikramaditya Roy',
      phone: '+91 98700 77777',
      wa: '+91 98700 77777',
      optIn: true,
      optInStatus: 'OPTED_IN' as const,
      optInSource: 'Web Form Opt-In',
      optInTimestamp: '18 Jul 2026, 17:10',
      city: 'Bangalore',
      lists: ['Existing Customers', 'Engineers'],
      lastMsg: '02 Aug 2026',
      tags: ['term', 'motor'],
      avatar: 'VR',
      color: 'bg-indigo-500',
      policyType: 'Term Life',
      sumInsured: '2 Crore',
      policyNo: 'MAX-2024-5412',
      expiryDate: '14-Sep-2026',
      premium: '₹22,800',
    },
    {
      id: 'C008',
      name: 'Ananya Deshmukh',
      phone: '+91 98800 88888',
      wa: '+91 98800 88888',
      optIn: false,
      optInStatus: 'PENDING_CONSENT' as const,
      optInSource: 'New Contact - Consent Pending',
      optInTimestamp: 'Pending Verification',
      city: 'Mumbai',
      lists: ['Doctors', 'Health Leads'],
      lastMsg: '—',
      tags: ['health', 'pending_consent'],
      avatar: 'AD',
      color: 'bg-teal-500',
      policyType: 'Health Top-Up',
      sumInsured: '50 Lakhs',
      policyNo: 'CARE-2024-9011',
      expiryDate: '29-Oct-2026',
      premium: '₹14,200',
    },
  ],

  // Detailed audience mappings for Automations
  automationAudiences: {
    A001: {
      automationId: 'A001',
      name: 'Renewal Reminder Series',
      targetCriteria: 'Policy Expiry between 1 to 45 days & Status = ACTIVE',
      totalCount: 4,
      contactIds: ['C001', 'C003', 'C005', 'C007'],
      excludedContactIds: [],
      qualificationDetails: {
        C001: { reason: 'Star Health SH-2024-88821 due in 28 days (20-Oct-2026)', nextStep: '30d reminder', scheduledFor: 'Today, 10:00 AM', status: 'QUEUED' },
        C003: { reason: 'ICICI Term ICICI-2024-33142 due in 14 days (01-Sep-2026)', nextStep: '15d reminder', scheduledFor: 'Today, 10:00 AM', status: 'SENT' },
        C005: { reason: 'HDFC Health HDFC-2023-9901 due in 6 days (24-Aug-2026)', nextStep: '7d reminder', scheduledFor: 'Today, 11:30 AM', status: 'QUEUED' },
        C007: { reason: 'Max Life MAX-2024-5412 due in 27 days (14-Sep-2026)', nextStep: '30d reminder', scheduledFor: 'Tomorrow, 10:00 AM', status: 'QUEUED' },
      },
    },
    A002: {
      automationId: 'A002',
      name: 'Installment Reminder',
      targetCriteria: 'Installment due in 6d, 3d or overdue 3d & Freq != YEARLY',
      totalCount: 2,
      contactIds: ['C003', 'C005'],
      excludedContactIds: [],
      qualificationDetails: {
        C003: { reason: 'Quarterly Installment ₹7,800 due on 01-Sep-2026', nextStep: '6d before', scheduledFor: '26 Aug, 09:00 AM', status: 'SCHEDULED' },
        C005: { reason: 'Monthly Installment ₹3,500 due on 24-Aug-2026', nextStep: '3d before', scheduledFor: '21 Aug, 09:00 AM', status: 'SCHEDULED' },
      },
    },
    A004: {
      automationId: 'A004',
      name: 'PHC Cycle Reminder',
      targetCriteria: 'Health Policy Active, PHC Not Availed, 120d-350d elapsed',
      totalCount: 3,
      contactIds: ['C002', 'C006', 'C008'],
      excludedContactIds: [],
      qualificationDetails: {
        C002: { reason: 'NIA Health ₹10,000 PHC benefit balance unused', nextStep: '240d reminder', scheduledFor: '22 Aug, 10:00 AM', status: 'QUEUED' },
        C006: { reason: 'Star Health ₹7,500 PHC checkup due in Pune', nextStep: '180d reminder', scheduledFor: '25 Aug, 10:00 AM', status: 'SCHEDULED' },
        C008: { reason: 'Care Health ₹15,000 Executive PHC unclaimed', nextStep: '300d reminder', scheduledFor: '28 Aug, 10:00 AM', status: 'SCHEDULED' },
      },
    },
    A005: {
      automationId: 'A005',
      name: 'Birthday Greetings',
      targetCriteria: 'Customer Birthday = Today & WhatsApp Opt-In = TRUE',
      totalCount: 1,
      contactIds: ['C006'],
      excludedContactIds: [],
      qualificationDetails: {
        C006: { reason: 'Birthday Today (18 Aug) · Dr. Kavita Joshi', nextStep: 'Birthday Greeting Card', scheduledFor: 'Today, 08:00 AM', status: 'SENT' },
      },
    },
    A006: {
      automationId: 'A006',
      name: 'Policy Thank-You',
      targetCriteria: 'Policy Created within 24 hours & Not already sent',
      totalCount: 2,
      contactIds: ['C001', 'C008'],
      excludedContactIds: [],
      qualificationDetails: {
        C001: { reason: 'New Star Optima policy issued', nextStep: 'Welcome Pack + Policy PDF', scheduledFor: 'Immediate', status: 'SENT' },
        C008: { reason: 'Care Super Top-up policy issued', nextStep: 'Welcome Pack + Policy PDF', scheduledFor: 'Immediate', status: 'SENT' },
      },
    },
  },

  // Detailed audience mappings for Campaigns
  campaignAudiences: {
    CAM001: {
      campaignId: 'CAM001',
      name: 'Diwali Greetings 2026',
      selectedLists: ['Doctors', 'Engineers', 'Existing Customers', 'Rotary'],
      contactIds: ['C001', 'C003', 'C005', 'C006', 'C007', 'C008'],
      excludedContactIds: ['C004'],
      filterRules: { optInOnly: true, excludeInvalid: true, cities: ['All'] },
    },
    CAM002: {
      campaignId: 'CAM002',
      name: 'Term Insurance Awareness',
      selectedLists: ['BNI Members', 'MF Leads', 'Existing Customers'],
      contactIds: ['C002', 'C003', 'C005', 'C007'],
      excludedContactIds: [],
      filterRules: { optInOnly: true, excludeInvalid: true, cities: ['Pune', 'Mumbai', 'Bangalore'] },
    },
    CAM003: {
      campaignId: 'CAM003',
      name: 'Health Check-up (PHC) Drive',
      selectedLists: ['Health Leads', 'Doctors'],
      contactIds: ['C001', 'C002', 'C006', 'C008'],
      excludedContactIds: [],
      filterRules: { optInOnly: true, excludeInvalid: true, cities: ['All'] },
    },
    CAM004: {
      campaignId: 'CAM004',
      name: 'Tax Saving ELSS & ULIP Season',
      selectedLists: ['Engineers', 'Doctors', 'BNI Members'],
      contactIds: ['C001', 'C003', 'C007'],
      excludedContactIds: ['C004'],
      filterRules: { optInOnly: true, excludeInvalid: true, cities: ['All'] },
    },
  },

  // Interactive Engaging Chatbot Configurations & Scenarios
  chatbotConfigs: [
    {
      id: 'BOT001',
      name: '24/7 Smart Insurance Assistant',
      description: 'Engaging general bot handling policy queries, quote calculation, renewals, and live agent handover with instant lead capture.',
      active: true,
      category: 'Customer Support & Sales',
      triggerKeywords: ['hi', 'hello', 'help', 'renew', 'quote', 'claim', 'insurance', 'plan'],
      leadStage: 'New WhatsApp Lead',
      assignedTo: 'Padmanabha Das',
      autoLeadCapture: true,
      stats: { triggered: 1480, resolved: 1120, leadsCaptured: 194, satisfaction: '96.4%' },
      welcomeMessage: '👋 Hello! Welcome to *InfoYashonanada Insurance*. I am your 24/7 AI Insurance Assistant.\n\nHow can I help you today? Please tap an option below:',
      quickReplies: [
        { id: 'qr_renew', label: '🔄 Policy Renewal', action: 'FLOW_RENEWAL' },
        { id: 'qr_quote', label: '📊 Instant Term / Health Quote', action: 'FLOW_QUOTE' },
        { id: 'qr_phc', label: '🏥 Free Health Checkup (PHC)', action: 'FLOW_PHC' },
        { id: 'qr_claim', label: '🚨 Claim Assistance', action: 'FLOW_CLAIM' },
        { id: 'qr_agent', label: '👤 Talk to Insurance Advisor', action: 'FLOW_AGENT' },
      ],
      nodes: {
        FLOW_RENEWAL: {
          title: 'Policy Renewal Assistance',
          botMessage: 'Great! Please reply with your *Policy Number* or *Registered Mobile Number*, and I will fetch your renewal details and discount options immediately.',
          options: ['Send Policy Number', 'Pay via UPI Link', 'Upgrade Sum Insured', 'Speak to Agent'],
          leadTriggerOn: 'Upgrade Sum Insured',
          suggestedInterest: 'Policy Renewal & Upgrade',
        },
        FLOW_QUOTE: {
          title: 'Instant Quote Calculator',
          botMessage: 'Which insurance cover are you looking to secure today?',
          options: ['🛡️ 1-2 Cr Term Life Cover', '🏥 ₹10-25 Lakh Health Cover', '🚗 Motor / Car Comprehensive', '📈 Mutual Funds & Tax Saving'],
          leadTriggerOn: 'ALL',
          suggestedInterest: 'New Insurance Quote',
        },
        FLOW_PHC: {
          title: 'Preventive Health Checkup',
          botMessage: 'Under your active health policy, you are entitled to a *₹10,000 complimentary health checkup* annually!\n\nWould you like me to book your slot at a partner diagnostic center in your city?',
          options: ['Book in Pune', 'Book in Mumbai', 'View Partner Diagnostic Labs', 'Share on WhatsApp'],
          leadTriggerOn: 'Book in Pune',
          suggestedInterest: 'Preventive Health Checkup (PHC)',
        },
        FLOW_CLAIM: {
          title: 'Emergency Claim Guidance',
          botMessage: '⚠️ *Cashless Hospitalization Notice*:\n\n1. For planned admissions, inform us 48 hours prior.\n2. For emergency admissions, intimation within 24 hours is required.\n\nOur claim desk is on standby to help you.',
          options: ['Intimate New Claim', 'Track Claim Status', 'Emergency Call Agent'],
          leadTriggerOn: 'Intimate New Claim',
          suggestedInterest: 'Active Claim Intimation',
        },
        FLOW_AGENT: {
          title: 'Human Advisor Handover',
          botMessage: 'I am connecting you with *Mr. Padmanabha Das (Agency Principal)*. He will review your request and call/message you within 15 minutes.\n\nWould you like to schedule a preferred callback time?',
          options: ['Morning (10 AM - 1 PM)', 'Afternoon (2 PM - 5 PM)', 'Evening (6 PM - 8 PM)', 'Call Immediately'],
          leadTriggerOn: 'Call Immediately',
          suggestedInterest: 'High-Intent Callback Request',
        },
      },
    },
    {
      id: 'BOT002',
      name: 'Instant Term Life Quote Bot',
      description: 'Interactive calculator that asks 3 quick questions (Age, Smoking, Cover Amount) and prepares an instant comparative quote with automatic CRM lead conversion.',
      active: true,
      category: 'Sales & Acquisition',
      triggerKeywords: ['term', 'life', '1cr', '2cr', 'death cover', 'quote'],
      leadStage: 'Qualified Opportunity',
      assignedTo: 'Padmanabha Das',
      autoLeadCapture: true,
      stats: { triggered: 840, resolved: 690, leadsCaptured: 142, satisfaction: '98.1%' },
      welcomeMessage: '🛡️ *Instant Term Life Insurance Calculator*\n\nGet up to ₹2 Crore cover starting at just ₹650/month with leading insurers (HDFC Life, ICICI Pru, Max Life).\n\nLet\'s calculate your quote in 30 seconds. What is your age group?',
      quickReplies: [
        { id: 'age_25_35', label: '21 - 35 Years', action: 'TERM_COVER' },
        { id: 'age_36_45', label: '36 - 45 Years', action: 'TERM_COVER' },
        { id: 'age_46_55', label: '46 - 55 Years', action: 'TERM_COVER' },
        { id: 'age_55_plus', label: '55+ Years', action: 'TERM_COVER' },
      ],
      nodes: {
        TERM_COVER: {
          title: 'Select Desired Sum Assured',
          botMessage: 'What is the sum assured required to protect your family?',
          options: ['₹1 Crore Cover (~₹590/mo)', '₹2 Crore Cover (~₹990/mo)', '₹3 Crore Cover (~₹1,450/mo)', 'Custom Amount'],
          leadTriggerOn: 'ALL',
          suggestedInterest: 'Term Life Insurance (High Value)',
        },
      },
    },
  ],

  contactLists: [
    { id: 'L001', name: 'Doctors', count: 145, icon: '👨‍⚕️', color: 'text-blue-600 bg-blue-50', lastUsed: '10 Aug 2026' },
    { id: 'L002', name: 'Engineers', count: 89, icon: '👷', color: 'text-purple-600 bg-purple-50', lastUsed: '05 Aug 2026' },
    { id: 'L003', name: 'BNI Members', count: 62, icon: '🤝', color: 'text-emerald-600 bg-emerald-50', lastUsed: '01 Aug 2026' },
    { id: 'L004', name: 'Health Leads', count: 234, icon: '🏥', color: 'text-amber-600 bg-amber-50', lastUsed: '15 Aug 2026' },
    { id: 'L005', name: 'MF Leads', count: 178, icon: '📈', color: 'text-rose-600 bg-rose-50', lastUsed: '18 Aug 2026' },
    { id: 'L006', name: 'Existing Customers', count: 412, icon: '⭐', color: 'text-cyan-600 bg-cyan-50', lastUsed: '18 Aug 2026' },
    { id: 'L007', name: 'Rotary', count: 48, icon: '🌐', color: 'text-pink-600 bg-pink-50', lastUsed: '12 Aug 2026' },
  ],

  media: [
    { id: 'M001', name: 'Diwali Flyer 2026', type: 'image', size: '850 KB', tags: ['Festival', 'Diwali'], emoji: '🪔', added: '15 Aug 2026' },
    { id: 'M002', name: 'PHC Benefit Card', type: 'image', size: '340 KB', tags: ['PHC', 'Health'], emoji: '🏥', added: '10 Jul 2026' },
    { id: 'M003', name: 'Claim Process Guide', type: 'pdf', size: '1.2 MB', tags: ['Claim', 'Health'], emoji: '📄', added: '01 Mar 2026' },
    { id: 'M004', name: 'Health Awareness Reel', type: 'video', size: '8.5 MB', tags: ['Health', 'Awareness'], emoji: '🎬', added: '10 Aug 2026' },
    { id: 'M005', name: 'MF Returns Infographic', type: 'image', size: '620 KB', tags: ['MF', 'Investment'], emoji: '📈', added: '12 Aug 2026' },
    { id: 'M006', name: 'Policy Renewal Card', type: 'image', size: '410 KB', tags: ['Renewal', 'Policy'], emoji: '🔄', added: '05 Aug 2026' },
  ],

  history: [
    {
      id: 'MSG001',
      customer: 'Rajesh Kumar',
      cId: 'C001',
      phone: '+91 98100 11111',
      type: 'Automation',
      source: 'Renewal Reminder Series',
      template: 'Renewal Reminder',
      templateId: 'T001',
      scheduled: '10 Aug, 10:00 AM',
      sent: '10 Aug, 10:01 AM',
      status: 'READ',
      errorCode: null,
      errorCategory: null,
      canRetry: false,
      detail: 'Delivered in 1.2s · Read at 10:45 AM · Converted to Lead 🎯',
    },
    {
      id: 'MSG002',
      customer: 'Priya Singh',
      cId: 'C002',
      phone: '+91 98200 22222',
      type: 'Automation',
      source: 'Renewal Reminder Series',
      template: 'Renewal Reminder',
      templateId: 'T001',
      scheduled: '10 Aug, 10:00 AM',
      sent: null,
      status: 'SKIPPED',
      errorCode: null,
      errorCategory: 'AUTO_STOP_RENEWED',
      canRetry: false,
      detail: 'Auto-Stop: Policy was already renewed on 08-Aug-2026',
    },
    {
      id: 'MSG003',
      customer: 'Amit Sharma',
      cId: 'C003',
      phone: '+91 98300 33333',
      type: 'Campaign',
      source: 'Term Cover 2Cr Upgrade Blitz',
      template: 'Term Plan Benefit',
      templateId: 'T002',
      scheduled: '15 Aug, 09:00 AM',
      sent: '15 Aug, 09:02 AM',
      status: 'READ',
      errorCode: null,
      errorCategory: null,
      canRetry: false,
      detail: 'Read at 11:20 AM · Customer replied for quotation 🎯',
    },
    {
      id: 'MSG004',
      customer: 'Sunita Devi',
      cId: 'C004',
      phone: '+91 98400 44444',
      type: 'Campaign',
      source: 'Health Awareness August',
      template: 'Health Awareness',
      templateId: 'T003',
      scheduled: '15 Aug, 09:00 AM',
      sent: null,
      status: 'FAILED',
      errorCode: '131026',
      errorCategory: 'INVALID_NUMBER',
      canRetry: true,
      detail: 'Meta Error 131026: Receiver phone number is not registered on WhatsApp or is a landline.',
    },
    {
      id: 'MSG005',
      customer: 'Mohan Lal',
      cId: 'C005',
      phone: '+91 98500 55555',
      type: 'Automation',
      source: 'Installment Reminder',
      template: 'Installment Reminder',
      templateId: 'T001',
      scheduled: '12 Aug, 11:00 AM',
      sent: '12 Aug, 11:00 AM',
      status: 'DELIVERED',
      errorCode: null,
      errorCategory: null,
      canRetry: false,
      detail: 'Delivered to handset · Installment 4 of 12 notification',
    },
    {
      id: 'MSG006',
      customer: 'Kavita Joshi',
      cId: 'C006',
      phone: '+91 98600 66666',
      type: 'Automation',
      source: 'Birthday Greetings',
      template: 'Birthday Wishes',
      templateId: 'T005',
      scheduled: '14 Aug, 08:00 AM',
      sent: '14 Aug, 08:01 AM',
      status: 'READ',
      errorCode: null,
      errorCategory: null,
      canRetry: false,
      detail: 'Birthday wishes delivered at 08:01 AM · Customer replied "🙏 धन्यवाद"',
    },
    {
      id: 'MSG007',
      customer: 'Anil Deshmukh',
      cId: 'C010',
      phone: '+91 98900 12345',
      type: 'Campaign',
      source: 'Term Cover 2Cr Upgrade Blitz',
      template: 'Renewal Reminder',
      templateId: 'T001',
      scheduled: '10 Aug, 11:00 AM',
      sent: null,
      status: 'FAILED',
      errorCode: '130429',
      errorCategory: 'RATE_LIMIT',
      canRetry: true,
      detail: 'Meta Error 130429: Cloud API throughput threshold reached. Ready for instant queue retry.',
    },
    {
      id: 'MSG008',
      customer: 'Vikram Rao',
      cId: 'C009',
      phone: '+91 98700 99999',
      type: 'Automation',
      source: 'PHC Cycle Reminder',
      template: 'PHC Reminder',
      templateId: 'T003',
      scheduled: '01 Aug, 09:00 AM',
      sent: null,
      status: 'SKIPPED',
      errorCode: null,
      errorCategory: 'AUTO_STOP_PHC_AVAILED',
      canRetry: false,
      detail: 'Auto-Stop: Customer completed annual PHC check-up on 28-Jul-2026',
    },
  ],
};
